#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="${SCRIPT_DIR}/dist"
WRK="$DIST_DIR/wrk"
NGINX="$DIST_DIR/nginx/sbin/nginx"
PID_FILE="$DIST_DIR/nginx/logs/nginx.pid"

# -- Defaults (match PTS profile)
THREADS="$(nproc)"
CONNECTIONS="100"
DURATION="90s"
URL="https://127.0.0.1:8089/test.html"
LATENCY=""
TIMEOUT=""
LUA_SCRIPT=""
EXTRA_HEADERS=()
KEEP_SERVER=""   # if set, don't start/stop nginx — assume it's already running
TARGET_RPS=""    # if set, inject a delay() Lua hook to throttle per-connection rate
TARGET_RPS_DIST="const"   # const | normal | exp | lognormal | pareto | onoff
REQUESTS=""      # if set, stop after ~this many total requests (-d becomes an upper bound)

# -- shape params for --rps-dist (overridable via config/rps-dist.sh)
: "${RPS_DIST_NORMAL_SIGMA_FACTOR:=0.333}"
: "${RPS_DIST_LOGNORMAL_SIGMA:=0.5}"
: "${RPS_DIST_PARETO_ALPHA:=1.5}"
: "${RPS_DIST_ONOFF_K:=10}"
: "${RPS_DIST_ONOFF_RATE_RATIO:=10}"
DIST_CONFIG="$SCRIPT_DIR/config/rps-dist.sh"
[[ -f "$DIST_CONFIG" ]] && source "$DIST_CONFIG"

for v in RPS_DIST_NORMAL_SIGMA_FACTOR RPS_DIST_LOGNORMAL_SIGMA \
         RPS_DIST_PARETO_ALPHA RPS_DIST_ONOFF_K RPS_DIST_ONOFF_RATE_RATIO; do
    val="${!v}"
    [[ "$val" =~ ^[0-9]+(\.[0-9]+)?$ ]] && (( $(awk "BEGIN{print ($val > 0)}") )) || {
        echo "ERROR: $v must be a positive number, got: $val" >&2; exit 1; }
done
WRK_TASKSET=()   # taskset prefix for wrk, populated if WRK_CORES is set

usage() {
    cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Options:
  -t THREADS      number of threads        (default: nproc = $(nproc))
  -c CONNECTIONS  concurrent connections   (default: 100)
  -d DURATION     test duration            (default: 90s)
  -n, --requests N stop after ~N total requests (approx; -d becomes an upper bound)
  -u URL          target URL               (default: https://127.0.0.1:8089/test.html)
  -s SCRIPT       LuaJIT script for wrk
  -H HEADER       add HTTP header (repeatable)
  --rps RPS       throttle to target requests/sec; 0 or inf = no throttle
  --rps-dist NAME inter-arrival distribution for --rps:
                  const|normal|exp|lognormal|pareto|onoff  (default: const)
  --latency       print detailed latency percentiles
  --timeout SEC   mark request failed after SEC seconds
  --keep-server   skip nginx start/stop (use if nginx is already running)
  -h              show this help

Environment:
  WRK_CORES       pin wrk threads to CPU cores, e.g. 0-3 or 0,2,4,6
                  (core count must equal -t THREADS)
EOF
    exit 0
}

# -- Argument parsing
while [[ $# -gt 0 ]]; do
    case "$1" in
        -t) THREADS="$2";     shift 2 ;;
        -c) CONNECTIONS="$2"; shift 2 ;;
        -d) DURATION="$2";    shift 2 ;;
        -n|--requests) REQUESTS="$2"; shift 2 ;;
        -u) URL="$2";         shift 2 ;;
        -s) LUA_SCRIPT="$2";  shift 2 ;;
        -H) EXTRA_HEADERS+=("$2"); shift 2 ;;
        --latency)      LATENCY="--latency"; shift ;;
        --timeout)      TIMEOUT="--timeout $2"; shift 2 ;;
        --rps)          TARGET_RPS="$2"; shift 2 ;;
        --rps-dist)     TARGET_RPS_DIST="$2"; shift 2 ;;
        --keep-server)  KEEP_SERVER=1; shift ;;
        -h|--help)      usage ;;
        *) echo "Unknown option: $1" >&2; usage ;;
    esac
done

[[ -x "$WRK" ]]   || { echo "ERROR: wrk not found — run install.sh first" >&2; exit 1; }
[[ -x "$NGINX" ]] || { echo "ERROR: nginx not found — run install.sh first" >&2; exit 1; }

# -- RPS throttle
TMPSCRIPT=""
if [[ -n "$TARGET_RPS" ]]; then
    case "${TARGET_RPS,,}" in
        0|inf|infinite)
            echo "RPS throttle: unlimited (no throttle)"
            ;;
        *)
            [[ "$TARGET_RPS" =~ ^[0-9]+$ ]] || { echo "ERROR: --rps must be a positive integer, 0, or inf" >&2; exit 1; }
            case "$TARGET_RPS_DIST" in
                const|normal|exp|lognormal|pareto|onoff) ;;
                *) echo "ERROR: --rps-dist must be one of: const, normal, exp, lognormal, pareto, onoff" >&2; exit 1 ;;
            esac
            DELAY_MS=$(awk -v c="$CONNECTIONS" -v r="$TARGET_RPS" 'BEGIN{printf "%d", int(c/r*1000 + 0.5)}')
            TMPSCRIPT="$(mktemp /tmp/wrk-delay-XXXXXX.lua)"
            cat > "$TMPSCRIPT" <<EOF
-- generated by bench.sh: --rps $TARGET_RPS --rps-dist $TARGET_RPS_DIST
local N = $DELAY_MS
local NORMAL_SIGMA_FACTOR = $RPS_DIST_NORMAL_SIGMA_FACTOR
local LOGNORMAL_SIGMA     = $RPS_DIST_LOGNORMAL_SIGMA
local PARETO_ALPHA        = $RPS_DIST_PARETO_ALPHA
local ONOFF_K             = $RPS_DIST_ONOFF_K
local ONOFF_RATE_RATIO    = $RPS_DIST_ONOFF_RATE_RATIO
math.randomseed(os.time())
EOF
            case "$TARGET_RPS_DIST" in
                const) cat >> "$TMPSCRIPT" <<'LUA'
function delay()
  return N
end
LUA
                    ;;
                normal) cat >> "$TMPSCRIPT" <<'LUA'
function delay()
  local u1 = math.random(); if u1 < 1e-12 then u1 = 1e-12 end
  local u2 = math.random()
  local z = math.sqrt(-2 * math.log(u1)) * math.cos(2 * math.pi * u2)
  local d = N + z * (N * NORMAL_SIGMA_FACTOR)
  if d < 0 then d = 0 end
  return d
end
LUA
                    ;;
                exp) cat >> "$TMPSCRIPT" <<'LUA'
function delay()
  return -N * math.log(1 - math.random())
end
LUA
                    ;;
                lognormal) cat >> "$TMPSCRIPT" <<'LUA'
function delay()
  local sigma = LOGNORMAL_SIGMA
  local mu = math.log(N) - sigma * sigma / 2
  local u1 = math.random(); if u1 < 1e-12 then u1 = 1e-12 end
  local u2 = math.random()
  local z = math.sqrt(-2 * math.log(u1)) * math.cos(2 * math.pi * u2)
  return math.exp(mu + sigma * z)
end
LUA
                    ;;
                pareto) cat >> "$TMPSCRIPT" <<'LUA'
function delay()
  local alpha = PARETO_ALPHA
  local x_m = N * (alpha - 1) / alpha
  return x_m * (1 - math.random()) ^ (-1 / alpha)
end
LUA
                    ;;
                onoff) cat >> "$TMPSCRIPT" <<'LUA'
local K = ONOFF_K
local d_on  = N / ONOFF_RATE_RATIO
local d_off = (K + 1) * N - K * d_on
local in_burst = (math.random() < 0.5)
local remaining = in_burst and K or 1
function delay()
  remaining = remaining - 1
  if remaining <= 0 then
    in_burst = not in_burst
    remaining = in_burst and K or 1
  end
  if in_burst then return d_on else return d_off end
end
LUA
                    ;;
            esac
            case "$TARGET_RPS_DIST" in
                const|exp) extra="" ;;
                normal)    extra=", sigma_factor=$RPS_DIST_NORMAL_SIGMA_FACTOR" ;;
                lognormal) extra=", sigma=$RPS_DIST_LOGNORMAL_SIGMA" ;;
                pareto)    extra=", alpha=$RPS_DIST_PARETO_ALPHA" ;;
                onoff)     extra=", K=$RPS_DIST_ONOFF_K, rate_ratio=$RPS_DIST_ONOFF_RATE_RATIO" ;;
            esac
            echo "RPS throttle: ${TARGET_RPS} req/s, dist=${TARGET_RPS_DIST}${extra}, mean delay=${DELAY_MS}ms per connection"
            [[ -n "$LUA_SCRIPT" ]] && echo "WARNING: --rps overrides -s (user Lua script ignored)"
            LUA_SCRIPT="$TMPSCRIPT"
            ;;
    esac
fi

# -- Request-count limiter
if [[ -n "$REQUESTS" ]]; then
    [[ "$REQUESTS" =~ ^[0-9]+$ ]] && (( REQUESTS > 0 )) || {
        echo "ERROR: --requests must be a positive integer, got: $REQUESTS" >&2; exit 1; }
    # split the total across threads; each thread stops after its own share
    PER_THREAD=$(awk -v n="$REQUESTS" -v t="$THREADS" 'BEGIN{printf "%d", int((n + t - 1) / t)}')
    if [[ -z "$TMPSCRIPT" ]]; then
        [[ -n "$LUA_SCRIPT" ]] && echo "WARNING: --requests overrides -s (user Lua script ignored)"
        TMPSCRIPT="$(mktemp /tmp/wrk-count-XXXXXX.lua)"
        echo "-- generated by bench.sh: --requests $REQUESTS" > "$TMPSCRIPT"
        LUA_SCRIPT="$TMPSCRIPT"
    fi
    cat >> "$TMPSCRIPT" <<EOF
-- request-count limiter (generated by bench.sh): stop after ~$REQUESTS total requests.
-- Each thread counts its own share; the first to finish sends SIGINT so wrk breaks out
-- of its duration sleep immediately and prints stats over the ACTUAL elapsed time.
local _ffi = require("ffi")
_ffi.cdef[[ int kill(int pid, int sig); int getpid(void); ]]
local _seen  = 0
local _limit = $PER_THREAD
function response(status, headers, body)
  _seen = _seen + 1
  if _seen >= _limit then
    wrk.thread:stop()
    _ffi.C.kill(_ffi.C.getpid(), 2)  -- 2 = SIGINT
  end
end
EOF
    echo "Request-count mode: total≈${REQUESTS} (${PER_THREAD}/thread × ${THREADS} threads); -d ${DURATION} is an upper bound"
fi

# -- CPU affinity for wrk threads
if [[ -n "${WRK_CORES:-}" ]]; then
    command -v taskset &>/dev/null || { echo "ERROR: taskset not found (install util-linux)" >&2; exit 1; }
    # NOTE: wrk is pinned via `taskset -c <real cpu id>`, not an nproc-wide
    # bitmask, so cores need only be online -- not < nproc. (nproc counts
    # online CPUs, which can be a sparse ID range, e.g. 0,2,4,...,22 when
    # SMT siblings are interleaved rather than offset by nproc/2.)
    expand_cpu_spec() {
        local spec=$1 tok lo hi c
        local IFS=','
        for tok in $spec; do
            if [[ "$tok" =~ ^([0-9]+)-([0-9]+)$ ]]; then
                lo="${BASH_REMATCH[1]}"; hi="${BASH_REMATCH[2]}"
                for (( c=lo; c<=hi; c++ )); do echo "$c"; done
            elif [[ "$tok" =~ ^[0-9]+$ ]]; then
                echo "$tok"
            fi
        done
    }
    ONLINE_CPUS=",$(expand_cpu_spec "$(cat /sys/devices/system/cpu/online 2>/dev/null)" | tr '\n' ','),"
    CORES=()
    IFS=',' read -ra TOKENS <<< "$WRK_CORES"
    for token in "${TOKENS[@]}"; do
        if [[ "$token" =~ ^([0-9]+)-([0-9]+)$ ]]; then
            lo="${BASH_REMATCH[1]}"; hi="${BASH_REMATCH[2]}"
            (( lo <= hi )) || { echo "ERROR: invalid range: $token" >&2; exit 1; }
            for (( c=lo; c<=hi; c++ )); do CORES+=("$c"); done
        elif [[ "$token" =~ ^[0-9]+$ ]]; then
            CORES+=("$token")
        else
            echo "ERROR: invalid core spec: $token" >&2; exit 1
        fi
    done
    for core in "${CORES[@]}"; do
        [[ "$ONLINE_CPUS" == *",$core,"* ]] || { echo "ERROR: core $core is not an online CPU" >&2; exit 1; }
    done
    if (( ${#CORES[@]} != THREADS )); then
        echo "ERROR: WRK_CORES lists ${#CORES[@]} core(s) but -t is ${THREADS}; counts must match" >&2
        exit 1
    fi
    WRK_CORE_LIST=$(IFS=,; echo "${CORES[*]}")
    WRK_TASKSET=(taskset -c "$WRK_CORE_LIST")
    echo "CPU affinity: wrk pinned to cores [${WRK_CORE_LIST}]"
fi

# -- Build wrk command
WRK_CMD=("${WRK_TASKSET[@]}" "$WRK" -t "$THREADS" -c "$CONNECTIONS" -d "$DURATION")
[[ -n "$LATENCY" ]]    && WRK_CMD+=("$LATENCY")
[[ -n "$TIMEOUT" ]]    && WRK_CMD+=($TIMEOUT)
[[ -n "$LUA_SCRIPT" ]] && WRK_CMD+=(-s "$LUA_SCRIPT")
for h in "${EXTRA_HEADERS[@]:-}"; do
    WRK_CMD+=(-H "$h")
done
WRK_CMD+=("$URL")

# -- Start nginx
nginx_started=""
if [[ -z "$KEEP_SERVER" ]]; then
    if [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
        echo "Using existing nginx (pid $(cat "$PID_FILE"))"
    else
        mkdir -p "$DIST_DIR/nginx/logs"
        "$NGINX" -p "$DIST_DIR/nginx" -c conf/nginx.conf
        sleep 2
        nginx_started=1
        echo "nginx started (pid $(cat "$PID_FILE"))"
    fi
fi

# -- Run benchmark
echo ""
echo "Running: ${WRK_CMD[*]}"
echo ""
"${WRK_CMD[@]}"

[[ -n "$TMPSCRIPT" ]] && rm -f "$TMPSCRIPT"

# -- Stop nginx
if [[ -n "$nginx_started" ]]; then
    "$NGINX" -p "$DIST_DIR/nginx" -c conf/nginx.conf -s quit
    echo ""
    echo "nginx stopped"
fi
